### ISSUE TITLE
CentOS 7 - error: Ignoring spamassassin because of bad file mode - must be 0644 or 0444.

### ISSUE THREAD

**Issue by tuxnice** [robertdebock/ansible-role-spamassassin#2]
## Describe the bug
Hello Robert, I used your role and got this next day:

```
/etc/cron.daily/logrotate:
error: Ignoring spamassassin because of bad file mode - must be 0644 or 0444.
```

You should consider to add `mode:` to your tasks. I changed it to 0644 and I will let you know if this error will happen again. 

with kind regards,
tuxnice

```yaml
---
- name: configure rsyslog
  template:
    src: spamassassin.conf.j2
    dest: /etc/rsyslog.d/spamassassin.conf
    mode: 0644
  notify:
    - restart rsyslog

- name: configure logrotate
  template:
    src: spamassassin.j2
    dest: /etc/logrotate.d/spamassassin
    mode: 0644
```

## Environment

- Control node Ansible version: 2.9.7
- Managed node OS: CentOS Linux release 7.8.2003 (Core)

Please consider [sponsoring me](https://github.com/sponsors/robertdebock).
